name: debug_window_example
description: Demonstrates how to use the sample plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  debug_window:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
