name: debug_window
description: This debug_window is an open-source library, in other words, a useful widget to enable you to confirm log or stream data in your flutter application.
version: 1.0.7
homepage: https://github.com/Ryotaewamoto/debug_window

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.1
