name: debug_window
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/Ryotaewamoto/debug_window

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.1
